blank_issues_enabled: false
contact_links:
  - name: 🤔 Preguntas y soporte
    about: Si tienes dudas sobre cómo usar Savepoint, por favor utiliza las discusiones.
    url: https://github.com/acensito/savepoint/discussions
